export enum NotificationChannel {
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  SMS = 'SMS',
  IN_APP = 'IN_APP',
}

export enum NotificationPriority {
  CRITICAL = 'CRITICAL',   
  HIGH = 'HIGH',         
  MEDIUM = 'MEDIUM',    
  LOW = 'LOW'             
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum NotificationType {
  // Billing
  BILL_CREATED = 'BILL_CREATED',
  BILL_CANCELLED = 'BILL_CANCELLED',
  RETURN_PROCESSED = 'RETURN_PROCESSED',
  
  // Wallet
  WALLET_CREDITED = 'WALLET_CREDITED',
  WALLET_DEBITED = 'WALLET_DEBITED',
  WALLET_EXPIRING = 'WALLET_EXPIRING',
  
  // Inventory
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  STOCK_RECEIVED = 'STOCK_RECEIVED',
  
  // Staff
  INCENTIVE_EARNED = 'INCENTIVE_EARNED',
  PERFORMANCE_REPORT = 'PERFORMANCE_REPORT',
  
  // Influencer
  COMMISSION_EARNED = 'COMMISSION_EARNED',
  COUPON_USED = 'COUPON_USED',
  
  // System
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  DAILY_REPORT = 'DAILY_REPORT',
  MONTHLY_SUMMARY = 'MONTHLY_SUMMARY',
  
  // Auth
  LOGIN_ALERT = 'LOGIN_ALERT',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED'
}